
 php:
    build: ./
    expose:
        - "9000"
    links:
        - db
    volumes:
        - ./:/var/www/html
 nginx:
    build: ./docker/nginx
    ports:
        - "80:80"
    links:
        - php
    volumes_from:
        - php

 db:
    build: ./docker/mysql
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: web
        MYSQL_USER: web
        MYSQL_PASSWORD: web
